#!/usr/bin/env node

const { cleanUrl } = require('../dist/utils/url');
const promptly = require('promptly');
const fetch = require('node-fetch');

require('dotenv').config();

const REMOTE_REQUEST_BIN_URL = process.env.REMOTE_REQUEST_BIN_URL;
if (!REMOTE_REQUEST_BIN_URL) {
  throw new Error('REMOTE_REQUEST_BIN_URL is required');
}

const REMOTE_REQUEST_BIN_PASSWORD = process.env.REMOTE_REQUEST_BIN_PASSWORD;

async function main() {
  const resetUrl = `${REMOTE_REQUEST_BIN_URL}/reset`;

  let password = REMOTE_REQUEST_BIN_PASSWORD || '';
  if (!REMOTE_REQUEST_BIN_PASSWORD || REMOTE_REQUEST_BIN_PASSWORD === '') {
    password = await promptly.password('Reset password: ');
  }

  const response = await fetch(resetUrl, {
    method: 'POST',
    body: JSON.stringify({ password }),
    headers: { 'Content-Type': 'application/json' },
  });
  const data = await response.json();
  return data;
}

main()
  .then(function (data) {
    console.log(data);
  })
  .catch(function (err) {
    console.error(err);
  });
